# Generated by Django 5.1.5 on 2025-02-18 04:39

import storages.backends.gcloud
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(storage=storages.backends.gcloud.GoogleCloudStorage(), upload_to='profile_pics'),
        ),
    ]
