# Generated by Django 4.2.11 on 2024-04-27 04:17

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sds_app", "0004_emailfileupload_body_rtf"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailfileupload",
            name="body_rtf_2",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
