# Generated by Django 4.2.11 on 2024-04-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sds_app", "0005_emailfileupload_body_rtf_2"),
    ]

    operations = [
        migrations.RemoveField(model_name="emailfileupload", name="body_rtf",),
    ]
