# Generated by Django 4.2.11 on 2024-06-03 04:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sds_app", "0007_alter_emailfileupload_body_rtf_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailfileupload",
            name="body_rtf_3",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
