# Generated by Django 4.2.11 on 2024-08-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sds_app", "0010_remove_emailfileupload_body_rtf_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailfileupload",
            name="delimiter",
            field=models.CharField(default=",", max_length=2),
        ),
    ]
