# Generated by Django 4.2.11 on 2024-08-24 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sds_app", "0011_alter_emailfileupload_delimiter"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingEmailSendsMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("campaign", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("sender_email", models.EmailField(max_length=254)),
                ("message_body", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(name="RecordingEmailSends",),
    ]
