# Generated by Django 4.2.11 on 2024-08-29 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sds_app", "0016_emailsendsmetadata_creator_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailfileupload",
            name="creator_id",
            field=models.ForeignKey(
                db_column="creator_id",
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailsendsmetadata",
            name="creator_id",
            field=models.ForeignKey(
                db_column="creator_id",
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recordingemailrecipients",
            name="creator_id",
            field=models.ForeignKey(
                db_column="creator_id",
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
