# Generated by Django 4.2.11 on 2024-08-30 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sds_app", "0017_alter_emailfileupload_creator_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(max_length=150)),
                ("company", models.CharField(max_length=150)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("salutation", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("ZIP", models.CharField(blank=True, max_length=10, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                ("web_site", models.CharField(blank=True, max_length=150, null=True)),
                ("notes", models.TextField()),
                (
                    "creator_id",
                    models.ForeignKey(
                        db_column="creator_id",
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
