# Generated by Django 5.1.5 on 2025-01-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_app', '0020_alter_customers_creator_id_alter_customers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_status', models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('email_content', models.TextField()),
                ('schedule_time', models.DateTimeField()),
            ],
        ),
    ]
