# Generated by Django 5.1.5 on 2025-02-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_app', '0023_requestconfig_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestconfig',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
    ]
