# Generated by Django 5.1.5 on 2025-02-17 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_app', '0024_requestconfig_completion_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailfileupload',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='emailsendsmetadata',
            name='creator_id',
        ),
        migrations.RemoveField(
            model_name='recordingemailrecipients',
            name='creator_id',
        ),
        migrations.CreateModel(
            name='EmailMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_status', models.CharField(max_length=10)),
                ('schedule_time', models.DateTimeField()),
                ('email_content', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='EmailFileUpload',
        ),
        migrations.DeleteModel(
            name='EmailSendsMetaData',
        ),
        migrations.DeleteModel(
            name='RecordingEmailRecipients',
        ),
    ]
