# Generated by Django 5.1.5 on 2025-02-18 04:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sds_app', '0025_email_remove_emailfileupload_creator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestconfig',
            name='email_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
