# Generated by Django 4.2.8 on 2025-10-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sds_app', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestconfig',
            name='reference_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestconfig',
            name='priority_status',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10),
        ),
    ]
