# Generated by Django 4.2.11 on 2024-04-05 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("emailscraper_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicCSVIngestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=150, verbose_name="email")),
                (
                    "HighSchools",
                    models.CharField(max_length=100, verbose_name="HighSchools"),
                ),
            ],
        ),
        migrations.DeleteModel(name="MyModel",),
        migrations.AlterField(
            model_name="emailoption",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
