# Generated by Django 4.2.11 on 2024-04-16 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("emailscraper_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailfileupload", old_name="creator", new_name="creator_id",
        ),
        migrations.AddField(
            model_name="emailfileupload",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
