# Generated by Django 4.2.11 on 2024-04-19 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emailscraper_app", "0002_rename_creator_emailfileupload_creator_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailfileupload",
            name="column_names",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="emailfileupload",
            name="delimiter",
            field=models.CharField(default=",", max_length=1),
        ),
        migrations.AlterField(
            model_name="emailfileupload",
            name="creator_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
