# Generated by Django 4.2.11 on 2024-04-25 20:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emailscraper_app", "0003_emailfileupload_column_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailfileupload",
            name="body_rtf",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
