# Generated by Django 4.2.11 on 2024-08-24 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emailscraper_app", "0009_recordingemailsends_delete_emailoption_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="emailfileupload", name="body_rtf_2",),
        migrations.RemoveField(model_name="emailfileupload", name="body_rtf_3",),
    ]
