# Generated by Django 4.2.11 on 2024-08-24 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emailscraper_app", "0012_recordingemailsendsmetadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailfileupload",
            name="creator_id",
            field=models.ForeignKey(
                db_column="creator_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
