# Generated by Django 4.2.11 on 2024-09-06 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "emailscraper_app",
            "0019_alter_customers_notes_customers_unique_email_creator",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customers",
            name="creator_id",
            field=models.ForeignKey(
                db_column="creator_id",
                default=1000000,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customers",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
