# Generated by Django 5.1.5 on 2025-02-05 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailscraper_app', '0022_requestconfig_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestconfig',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
