# Generated by Django 4.2.8 on 2025-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailscraper_app', '0028_requestconfig_reference_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestconfig',
            name='reference_tag',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
