# Generated by Django 4.2.8 on 2025-10-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailscraper_app', '0029_alter_requestconfig_reference_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestconfig',
            name='request_title',
            field=models.CharField(default='Title', max_length=150),
            preserve_default=False,
        ),
    ]
